In [ ]:
import pandas as pd

In [ ]:
from google.colab import files
uploaded = files.upload()

In [ ]:
review_df=pd.read_csv('tripadvisor_hotel_reviews.csv')

In [ ]:
review_df.head()

                                              Review  Rating
0  nice hotel expensive parking got good deal sta...       4
1  ok nothing special charge diamond member hilto...       2
2  nice rooms not 4* experience hotel monaco seat...       3
3  unique, great stay, wonderful time hotel monac...       5
4  great stay great stay, went seahawk game aweso...       5

In [ ]:
import re
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import nltk

In [ ]:
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

In [ ]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [ ]:
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...

True

In [ ]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re



# Initialize
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

# Function to clean text
def clean_review(text):
    text = str(text).lower()
    text = re.sub(r'[^a-z\s]', '', text)  # remove punctuation/numbers
    words = text.split()
    words = [lemmatizer.lemmatize(w) for w in words if w not in stop_words]
    return ' '.join(words)

# Apply to your DataFrame
review_df['Review'] =review_df['Review'].apply(clean_review)

In [ ]:
def rating_to_sentiment(rating):
    if rating <= 2:
        return 'negative'
    elif rating == 3:
        return 'neutral'
    else:
        return 'positive'

review_df['sentiment'] = review_df['Rating'].apply(rating_to_sentiment)

In [ ]:
review_df.head()

                                              Review  Rating sentiment
0  nice hotel expensive parking got good deal sta...       4  positive
1  ok nothing special charge diamond member hilto...       2  negative
2  nice room experience hotel monaco seattle good...       3   neutral
3  unique great stay wonderful time hotel monaco ...       5  positive
4  great stay great stay went seahawk game awesom...       5  positive

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(max_features=5000)
X_reviews = vectorizer.fit_transform(review_df['Review'])
y = review_df['sentiment']  # target

In [ ]:
X = vectorizer.fit_transform(review_df['Review'])

In [ ]:
y=review_df['sentiment']

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report,confusion_matrix

In [ ]:
lr_model=LogisticRegression(max_iter=5000)
lr_model.fit(X_train,y_train)

LogisticRegression(max_iter=5000)

In [ ]:
y_pred = lr_model.predict(X_test)

In [ ]:
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[ 476   40  109]
 [  91   89  252]
 [  36   39 2967]]
              precision    recall  f1-score   support

    negative       0.79      0.76      0.78       625
     neutral       0.53      0.21      0.30       432
    positive       0.89      0.98      0.93      3042

    accuracy                           0.86      4099
   macro avg       0.74      0.65      0.67      4099
weighted avg       0.84      0.86      0.84      4099

In [ ]:
input_review=["unique great stay wonderful time hotel monaco "]


#convert text to feature vectors
input_data_features=vectorizer.transform(input_review)

#making prediction
prediction=lr_model.predict(input_data_features)
print(prediction)

['positive']